config/routes.rb
Rails.application.routes.draw do
  root :to => 'posts#index'

  resources :users
  resources :posts do
    resources :comments, :except => [:show, :index]
  end

  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :body, :presence => true

  after_create :send_message

private
  def send_message
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => 'There is a new comment on your post.',
                      :To => to,
                      :From => ENV['FROM'] }
      ).execute
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  validates :title, :presence => true
  validates :body, :presence => true
end

app/models/session.rb
class Session < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password

  has_many :posts
  has_many :comments

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_path(@comment.post) }
        format.js
      end
      flash[:notice] = "Comment successfully added!"
    else
      flash[:alert] = "There was a problem adding your comment."
      redirect_to post_path(@comment.post)
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "Comment successfully updated!"
      redirect_to post_path(@comment.post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    flash[:notice] = "Comment successfully deleted."
    redirect_to post_path(@comment.post)
  end

private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post successfully added!"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post successfully updated!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Post successfully deleted."
    redirect_to posts_path
  end

private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to posts_path(@user.id)
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
  end

private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<li>
  <div class="well">
  <p><%= comment.body %></p>
    <% if current_user != nil %>
      <p><%= link_to "Edit comment", edit_post_comment_path(@post, comment) %></p>
      <p><%= link_to "Delete comment", post_comment_path(@post, comment),
                                  :data => {:method => "delete"} %></p>
    <% end %>
  </div>
</li>

app/views/comments/_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

<%= form_for [@post, @comment], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('#comments').append('<%= j render(@comment) %>');
$('#new_comment').hide();
$('#add_comment').show();

app/views/comments/edit.html.erb
<% content_for(:title, "Edit Comment | #{@post.title}") %>

<h1>Edit comment for <%= @post.title %></h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<% content_for(:title, "New Comment | #{@post.title}") %>

<h1>New comment for <%= @post.title %></h1>

<%= render 'form' %>

app/views/comments/new.js.erb
$('#add_comment').hide().after('<%= j render("form") %>');

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <%= object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <% if current_user == nil %>
          <li><%= link_to "Register", new_user_path %></li>
          <li><%= link_to "Log in", new_session_path %> </li>
        <% else %>
          <li><a>Logged in as <strong><%= current_user.email %></strong></a></li>
          <li><%= link_to "Log out", session_path(session), :data => {:method => "delete"} %></li>
        <% end %>
      </ul>
    </nav>

    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>

  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.label :body %>
  <%= f.text_area :body, :class => 'form-control' %>
  </div>
  <div class="form-group">
  <%= f.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% content_for(:title, "Edit #{@post.title}") %>

<h1>Edit <%= @post.title %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for(:title, "Blog Posts") %>

<h1>Posts</h1>

<div class="well">
  <ul class='list-unstyled'>
    <% @posts.each do |post| %>
      <li><%= link_to post.title, post_path(post) %></li>
    <% end %>
  </ul>
</div>

<% if current_user != nil %>
  <p><%= link_to "Create a new post", new_post_path %></p>
<% end %>

app/views/posts/new.html.erb
<% content_for(:title, "New Post") %>

<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for(:title, "#{@post.title}") %>

<h1><%= @post.title %></h1>

<div class="well">
  <p><%= @post.body %></p>

  <% if current_user != nil %>
    <p><%= link_to "Edit post", edit_post_path(@post) %></p>
    <p><%= link_to "Delete post", post_path(@post),
                              :data => {:method => "delete"} %></p>
  <% end %>
</div>

  <ul id='comments', class='list-unstyled'>
      <% @post.comments.each do |comment| %>
        <%= render comment %>
      <% end %>
  </ul>

<% if current_user != nil %>
  <p><%= link_to "Add a comment", new_post_comment_path(@post), id: "add_comment", remote: true %></p>
<% end %>


<p><%= link_to "Return to posts", posts_path %></p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%=form_for User.new do |f| %>
  <div class="form-group">
    <%=f.label :email %>
    <%=f.text_field :email %>
  </div>
  <div class="form-group">
    <%=f.label :phone_number %>
    <%=f.text_field :phone_number %>
  </div>
  <div class="form-group">
    <%=f.label :password %>
    <%=f.password_field :password %>
  </div>
  <div class="form-group">
    <%=f.label :password_confirmation %>
    <%=f.password_field :password_confirmation %>
  </div>
  <div class="form-group">
    <%=f.submit "Sign Up" %>
  </div>
<%end%>